name: Build

on:
  push:
    branches: [main]

jobs:
  build-win:
    name: Build Windows
    runs-on: windows-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@master
      - name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@v2
        with:
            version: "18.1.8"
      - name: Download Toolchain
        id: toolchain-download
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          target: x86_64-pc-windows-gnu
          toolchain: stable
          rustflags: "" # i dont want warnings to be errors
      - name: Compile
        id: compile
        run: cargo build --release
        env:
          LIBCLANG_PATH: ${{ env.LLVM_PATH }}/lib
      - name: Archive Build 
        run: Compress-Archive -Path target/release/audiopipe.exe -DestinationPath audiopipe.zip
        shell: pwsh
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: Binary
          path: audiopipe.zip
  build-linux:
    name: Build Linux
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@master
      - name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@v2
        with:
            version: "18.1.8"
      - name: Download Toolchain
        id: toolchain-download
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          target: x86_64-unknown-linux-gnu
          toolchain: stable
          rustflags: "" # i dont want warnings to be errors
      - name: Compile
        id: compile
        run: cargo build --release
        env:
          LIBCLANG_PATH: ${{ env.LLVM_PATH }}/lib
      - name: Archive Build 
        run: tar -czvf audiopipe.tar.gz -C target/release audiopipe
        shell: bash
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: Binary
          path: audiopipe.tar.gz
  build-mac:
    name: Build MacOS
    runs-on: macos-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@master
      - name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@v2
        with:
            version: "18.1.8"
      - name: Download Toolchain
        id: toolchain-download
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          target: x86_64-unknown-linux-gnu
          toolchain: stable
          rustflags: "" # i dont want warnings to be errors
      - name: Compile
        id: compile
        run: cargo build --release
        env:
          LIBCLANG_PATH: ${{ env.LLVM_PATH }}/lib
      - name: Archive Build 
        run: zip -9r audiopipe.zip target/release/audiopipe
        shell: bash
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: Binary
          path: audiopipe.zip
