name: Build

on:
  push:
    branches: [main]

jobs:
  build-win:
    name: Build Windows
    runs-on: windows-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@master
      - name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@v2
        with:
            version: "18.1.8"
      - name: Compile
        id: compile
        uses: rust-build/rust-build.action@v1.4.5
        with:
          RUSTTARGET: x86_64-pc-windows-gnu
          ARCHIVE_TYPES: zip
          UPLOAD_MODE: none
          TOOLCHAIN_VERSION: stable
        env:
          LIBCLANG_PATH: ${{ env.LLVM_PATH }}/lib
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: Binary
          path: |
            ${{ steps.compile.outputs.BUILT_ARCHIVE }}
            ${{ steps.compile.outputs.BUILT_CHECKSUM }}
  build-linux:
    name: Build Linux
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@master
      - name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@v2
        with:
            version: "18.1.8"
      - name: Compile
        id: compile
        uses: rust-build/rust-build.action@v1.4.5
        with:
          RUSTTARGET: x86_64-unknown-linux-musl
          ARCHIVE_TYPES: tar.gz tar.xz tar.zst
          UPLOAD_MODE: none
          TOOLCHAIN_VERSION: stable
        env:
          LIBCLANG_PATH: ${{ env.LLVM_PATH }}/lib
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: Binary
          path: |
            ${{ steps.compile.outputs.BUILT_ARCHIVE }}
            ${{ steps.compile.outputs.BUILT_CHECKSUM }}
  build-mac:
    name: Build MacOS
    runs-on: macos-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@master
      - name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@v2
        with:
            version: "18.1.8"
      - name: Compile
        id: compile
        uses: rust-build/rust-build.action@v1.4.5
        with:
          RUSTTARGET: x86_64-apple-darwin
          ARCHIVE_TYPES: zip
          UPLOAD_MODE: none
          TOOLCHAIN_VERSION: stable
        env:
          LIBCLANG_PATH: ${{ env.LLVM_PATH }}/lib
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: Binary
          path: |
            ${{ steps.compile.outputs.BUILT_ARCHIVE }}
            ${{ steps.compile.outputs.BUILT_CHECKSUM }}